# Generated by Django 5.2.3 on 2025-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tag_alter_task_user_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
